language: csharp
mono: none
dotnet: 2.2.100

env:
  global:
  - PACKAGE_NAME=SmartGlassCli-$TRAVIS_BRANCH-$TRAVIS_OS_NAME

matrix:
  include:
  - os: linux
    dist: xenial
    env: PUBLISH_TARGET=linux-x64 BUILD_CONFIG=Release
  - os: osx
    osx_image: xcode9.2
    env: PUBLISH_TARGET=osx.10.12-x64 BUILD_CONFIG=Release

script:
- dotnet --info
- dotnet restore
- dotnet test Tests/SmartGlass
- dotnet test Tests/SmartGlass.Common
- dotnet test Tests/SmartGlass.Cli
- dotnet test Tests/SmartGlass.Nano
- dotnet build -c $BUILD_CONFIG
- dotnet publish -c $BUILD_CONFIG -r $PUBLISH_TARGET -o $PACKAGE_NAME SmartGlass.Cli

before_deploy:
- cd SmartGlass.Cli/$PACKAGE_NAME
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r $TRAVIS_BUILD_DIR/$PACKAGE_NAME.zip .; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar czvf $TRAVIS_BUILD_DIR/$PACKAGE_NAME.tar.gz *; fi
- cd ..

deploy:
  - provider: releases
    api_key:
      secure: Gxxr2fwF4ujUwXrhT/uF/SrAt0BF3B2O1Qy9emrD/zCZNFixYQYPaeoBeJeFNBjzU+t3ekxY+gV37pk+iAQ0xLxC97aviWtNIRivMR69PmHT9Mj6H7MWXaUci4vLoggZuX6EcqCpaYiFupZZZnawKpi01H+dLbQUseZSBOnqIc4IBABAG0iWIfcu1e5iAvg+I0O3MRdYiW9pGKm1mBtuo+f3qQFdKRS7ZlfyfjVWtSLvFPxWquw71af7311CKmWua6S2XGqWAiO0Dsfl65zEBZlcbTnD2/SkcbM0JTMkfa2+Eht+B496j0F7mECJLg7Y3SOg7ASNlHO+CrM4+nB7316gWgNs9wNPgLswMAErxN2pnKiIsD496fBXQByAJyl+ABXh0JLyNcz3ZEl8z6ZdChR8F4OjvGCnl78eP7qAPPtQmXPy41dU4ytJS2tNnh3XVqyq6LPSsUYseiQ1y0qeSXSd7Qvg7pX4hHit6XH8FK9yBK8AR4DQcrmvJa3vSpkreJwtE+F40zIDs9qWLAGGG5WXWJnWyc6Im05Fyal8dA++R4ppjC8TDAziUlk1AdP+jnzKdVDjb/NIkeJjGY9N1tb2y6IewdgItLARghpn+XZkGd+H+RjZCcezGqMhoJmQScR/w+njE7KIgJQFcHEBm0dWVl4hVWfylsj0jyQkZtI=
    file: $TRAVIS_BUILD_DIR/$PACKAGE_NAME.tar.gz
    skip_cleanup: true
    on:
      tags: true
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key:
      secure: Gxxr2fwF4ujUwXrhT/uF/SrAt0BF3B2O1Qy9emrD/zCZNFixYQYPaeoBeJeFNBjzU+t3ekxY+gV37pk+iAQ0xLxC97aviWtNIRivMR69PmHT9Mj6H7MWXaUci4vLoggZuX6EcqCpaYiFupZZZnawKpi01H+dLbQUseZSBOnqIc4IBABAG0iWIfcu1e5iAvg+I0O3MRdYiW9pGKm1mBtuo+f3qQFdKRS7ZlfyfjVWtSLvFPxWquw71af7311CKmWua6S2XGqWAiO0Dsfl65zEBZlcbTnD2/SkcbM0JTMkfa2+Eht+B496j0F7mECJLg7Y3SOg7ASNlHO+CrM4+nB7316gWgNs9wNPgLswMAErxN2pnKiIsD496fBXQByAJyl+ABXh0JLyNcz3ZEl8z6ZdChR8F4OjvGCnl78eP7qAPPtQmXPy41dU4ytJS2tNnh3XVqyq6LPSsUYseiQ1y0qeSXSd7Qvg7pX4hHit6XH8FK9yBK8AR4DQcrmvJa3vSpkreJwtE+F40zIDs9qWLAGGG5WXWJnWyc6Im05Fyal8dA++R4ppjC8TDAziUlk1AdP+jnzKdVDjb/NIkeJjGY9N1tb2y6IewdgItLARghpn+XZkGd+H+RjZCcezGqMhoJmQScR/w+njE7KIgJQFcHEBm0dWVl4hVWfylsj0jyQkZtI=
    file: $TRAVIS_BUILD_DIR/$PACKAGE_NAME.zip
    skip_cleanup: true
    on:
      tags: true
      branch: master
      condition: $TRAVIS_OS_NAME = osx