version: 1.0.{build}
image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Release

before_build:
  - cmd: nuget restore

build:
  publish_nuget: true
  verbosity: minimal

after_build:
  - cmd: echo "Building publishable package for Windows %PLATFORM%"
  - cmd: dotnet publish -c Release -r win-%PLATFORM% -o win-%PLATFORM% SmartGlass.Cli
  - cmd: 7z a SmartGlassCli-%APPVEYOR_REPO_TAG_NAME%-windows-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\SmartGlass.Cli\win-%PLATFORM%\*

artifacts:
  - path: '*.zip'
    name: cli
    type: Zip

deploy:
  - provider: NuGet
    api_key:
      secure: wIdVJb80C4XWefa1hpb3XYrsOjoEjzZQ/pR+N/89qOoOH4elogXFPZabqNtdv72h
    skip_symbols: false
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
  - provider: GitHub
    description: 'SmartGlass Cli'
    artifact: cli
    auth_token:
      secure: qglMtUCbrzIn+36s7qWOPEj0HmJgs99bnzi4K8uYNPoxGW0qmJdOD1lmsa3TzGPn
    draft: false
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
